index_title: 404Cookbook
index_description: Recettes maison, partagées en famille.

show_images_on_index: true

lang: fr
strings:
  search_placeholder: Rechercher…
  uncategorized_label: Non catégorisé
  source_label: Source
  vegan_label: Végane
  meat_label: Viande
  spicy_label: Épicé
  sweet_label: Sucré
  salty_label: Salé
  sour_label: Acide
  bitter_label: Amer
  umami_label: Umami
  footer_text: Bon appétit !
  updated_on: Mis à jour le
  edit: Modifier

github_url: https://github.com/404loopback/404Cookbook

deploy_remote:
